# =========================
# 1. Builder stage
# =========================
FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependency files first (cache-friendly)
COPY my-blog/package.json my-blog/package-lock.json ./
RUN npm ci

# Copy source code and build
COPY my-blog/ .
RUN npm run build


# =========================
# 2. Runtime stage
# =========================
FROM node:22-alpine AS runtime

WORKDIR /app



# Copy only runtime artifacts
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

ENV HOSTNAME=0.0.0.0
ENV PORT=3000


EXPOSE 3000
CMD ["node", "server.js"]
